### PR TITLE
upgrade zkevm-circuits

### PR DESCRIPTION
**Pull request by lispc**

### CODE REVIEW

**Comment by lightsing** [comment]
testing on super2 following mainnet, fix #11

**Comment by lispc** [comment]
can you use numbers here? https://github.com/scroll-tech/zkevm-circuits/blob/develop/eth-types/src/forks.rs

**Comment by lightsing** [comment]
> can you use numbers here? https://github.com/scroll-tech/zkevm-circuits/blob/develop/eth-types/src/forks.rs

updated

**Comment by lispc** [comment]
we may have multi hardforks in futures.  So method signature can be a bit more general.   We will have curie / dirac / exxx hardforks.

**Comment by lightsing** [comment]
> we may have multi hardforks in futures. So method signature can be a bit more general. We will have curie / dirac / exxx hardforks.

changed

**Comment by lightsing** [comment]
testing with sepolia test net

**Comment by lightsing** [comment]
I think it's ready to merge

**Pull request merged**
